image:
  pullPolicy: IfNotPresent
  repository: deluan/navidrome
  tag: 0.60.0@sha256:5d0f6ab343397c043c7063db14ae10e4e3980e54ae7388031cbce47e84af6657
persistence:
  data:
    enabled: true
    mountPath: /data
  music:
    enabled: true
    mountPath: /music
portal:
  open:
    enabled: true
service:
  main:
    ports:
      main:
        port: 4533
        targetPort: 4533
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ND_ENABLETRANSCODINGCONFIG: false
            ND_LOGLEVEL: info
            ND_MUSICFOLDER: /music
            ND_SCANSCHEDULE: '@every 15m'
            ND_SESSIONTIMEOUT: 24h
