image:
  pullPolicy: IfNotPresent
  repository: jc21/nginx-proxy-manager
  tag: 2.13.6@sha256:669be1a294d4491b842f542d238ea1d4bca8f76fbedd7d99b45b24cd5a8cff99
mariadb:
  enabled: true
  includeCommon: true
  mariadbDatabase: npm
  mariadbUsername: npm
persistence:
  data:
    enabled: true
    mountPath: /data
    size: 256Gi
  letsencrypt:
    enabled: true
    mountPath: /etc/letsencrypt
    size: 256Gi
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10582
        protocol: http
        targetPort: 81
  web:
    enabled: true
    ports:
      web:
        enabled: true
        port: 10583
        protocol: http
        targetPort: 80
  websecure:
    enabled: true
    ports:
      websecure:
        enabled: true
        port: 10584
        protocol: https
        targetPort: 443
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DB_MYSQL_HOST:
              secretKeyRef:
                expandObjectName: false
                key: plainhost
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
            DB_MYSQL_NAME: '{{ .Values.mariadb.mariadbDatabase }}'
            DB_MYSQL_PASSWORD: '{{ .Values.mariadb.password }}'
            DB_MYSQL_PORT: 3306
            DB_MYSQL_USER: '{{ .Values.mariadb.mariadbUsername }}'
            DISABLE_IPV6: true
          probes:
            liveness:
              custom: true
              enabled: true
              spec:
                exec:
                  command:
                  - /bin/check-health
            readiness:
              custom: true
              enabled: true
              spec:
                exec:
                  command:
                  - /bin/check-health
            startup:
              custom: true
              enabled: true
              spec:
                exec:
                  command:
                  - /bin/check-health
